### ISSUE TITLE
DP 실행 관련 질문

### ISSUE THREAD

**Issue by YejinK** [sgnlplabeling/nlp_labeling#27]
안녕하세요,

DP 실행 관련 질문입니다. 제가 examples/run_graphParser.sh 실행하는데 gensim과 h5py, overrides, tarjan 등등 라이브러리 들을 설치해야 했는데요, 첫번째로 혹시 requirements.txt를 만들어 주실 수 있나요? README.md에는
python == 3.6.9
pytorch == 1.1.0
cuda == 10.0
만 언급되어 있고 다른 라이브러리들은 따로 설치 과정이 없어 run_graphParser.sh를 실행하면 프로그램이 돌아갈 때 까지 모든 package를 일일이 설치해줘야 하는것 같습니다.
그리고 두번째로 packge 설치 후에는 이런 에러가 발생합니다.

Traceback (most recent call last):
  File "examples/GraphParser.py", line 23, in <module>
    from neuronlp2.io import get_logger, conllx_data
  File "./neuronlp2/__init__.py", line 7, in <module>
    from . import models
  File "./neuronlp2/models/__init__.py", line 4, in <module>
    from .parsing import *
  File "./neuronlp2/models/parsing.py", line 20, in <module>
    from bert.bert_for_embedding import BertForEmbedding, BertForEncoder, make_bert_input, resize_bert_output,\
ModuleNotFoundError: No module named 'bert'

bert라는 패키지가 있는 줄 알고 pip install bert를 실행 했는데 이후에는 다음과 같은 에러가 발생합니다.

Traceback (most recent call last):
  File "examples/GraphParser.py", line 23, in <module>
    from neuronlp2.io import get_logger, conllx_data
  File "./neuronlp2/__init__.py", line 7, in <module>
    from . import models
  File "./neuronlp2/models/__init__.py", line 4, in <module>
    from .parsing import *
  File "./neuronlp2/models/parsing.py", line 20, in <module>
    from bert.bert_for_embedding import BertForEmbedding, BertForEncoder, make_bert_input, resize_bert_output,\
ModuleNotFoundError: No module named 'bert.bert_for_embedding'

이 모듈은 혹시 어떻게 받을 수 있나요?

**Comment by boychaboy** [comment]
BERT같은 경우에는 atree에서 제공하는 BERT를 사용했습니다. 아래 링크에서 BERT Pre-trained model 신청을 하신 후에 모델을 다운로드 받으셔서 실행해주시면 됩니다. 
http://aiopen.etri.re.kr/service_dataset.php
